version: '2'
services:
  hadoop-master:
    hostname: hadoop-master
    image: 'teradatalabs/mapr52-hive'
    privileged: true
    ports:
      - '1180:1180'
      - '8020:8020'
      - '8088:8088'
      - '9083:9083'
      - '10000:10000'
      - '50070:50070'
      - '50075:50075'
      - '7222:7222'
    volumes:
      - ../../presto-hive/src/test/sql:/files/sql:ro
      - ./files/words:/usr/share/dict/words:ro
  dnsmasq:
    hostname: dnsmasq
    image: 'teradatalabs/dns:2.75-4e54a19'
    cap_add:
      - NET_ADMIN
    ports:
      - '5354:53/udp'
